name: "Étape 4 - Authentification (Password Hash + Login + JWT)"
description: "Implémenter la logique d’authentification : hash du mot de passe, login, génération et vérification des JWT/refresh tokens."
title: "[Étape 4] Authentification et JWT"
labels:
  - backend
  - auth
  - jwt
  - étape-4
assignees:
  - copilothub[bot]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔐 Étape 4 - Authentification (Password Hash + JWT)

        Cette étape implémente la logique d'authentification pour ton SSO :
        - Hashage sécurisé des mots de passe avec bcrypt
        - Endpoint `/register` pour créer un utilisateur
        - Endpoint `/login` pour authentifier un utilisateur
        - Génération d’un JWT (access token) et d’un refresh token
        - Vérification de la validité du token pour les routes protégées

  - type: textarea
    id: dependencies
    attributes:
      label: Dépendances à installer
      description: Liste des paquets nécessaires pour la gestion du hash et des tokens JWT.
      value: |
        ```bash
        npm install bcrypt jsonwebtoken
        npm install --save-dev @types/jsonwebtoken @types/bcrypt
        ```
    validations:
      required: true

  - type: textarea
    id: auth_logic
    attributes:
      label: Structure de la logique d'authentification
      description: Exemple de logique à implémenter (hash, login, JWT).
      value: |
        ```ts
        import bcrypt from "bcrypt"
        import jwt from "jsonwebtoken"
        import { PrismaClient } from "@prisma/client"

        const prisma = new PrismaClient()
        const JWT_SECRET = process.env.JWT_SECRET || "changeme"

        // 🧩 Hash du mot de passe
        async function hashPassword(password: string) {
          return await bcrypt.hash(password, 10)
        }

        // ✅ Vérification du mot de passe
        async function verifyPassword(password: string, hash: string) {
          return await bcrypt.compare(password, hash)
        }

        // 🔑 Génération du token JWT
        function generateAccessToken(userId: string) {
          return jwt.sign({ userId }, JWT_SECRET, { expiresIn: "15m" })
        }

        // 🔁 Génération du refresh token
        function generateRefreshToken(userId: string) {
          return jwt.sign({ userId, type: "refresh" }, JWT_SECRET, { expiresIn: "7d" })
        }
        ```

  - type: input
    id: env_vars
    attributes:
      label: Variables d'environnement à ajouter
      description: Clés nécessaires pour la signature des tokens.
      placeholder: JWT_SECRET="un_secret_très_long_et_sécurisé"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **Checklist :**
        - [ ] Hash du mot de passe fonctionnel à l’inscription
        - [ ] Vérification correcte à la connexion
        - [ ] JWT signé avec `JWT_SECRET`
        - [ ] Refresh token stocké et validé
        - [ ] Routes protégées accessibles uniquement avec un JWT valide
