name: "Étape 6 – Frontend SSO (Login & Register)"
description: "Implémenter l'interface SSO : pages /register et /login, connexion au backend, stockage du JWT."
title: "✨ [Étape 6] Frontend SSO — Login / Register"
labels:
  - frontend
  - sso
  - nextjs
  - ui
assignees:
  - github-copilot
  - YOUR_GITHUB_USERNAME
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objectif
        Créer une interface Next.js simple et sécurisée pour l'inscription et la connexion des utilisateurs,
        connecter le front au backend SSO et gérer le token JWT côté client.

  - type: markdown
    attributes:
      value: |
        ## 🧩 Stack recommandée
        - Next.js (app router)
        - TailwindCSS
        - Axios (ou fetch)
        - React Hook Form (+ Zod pour validation optionnelle)

  - type: markdown
    attributes:
      value: |
        ## ✅ Tâches (Checklist)
  - type: markdown
    attributes:
      value: |
        - [ ] Créer un projet Next.js (ou dossier `frontend/` dans le repo)
        - [ ] Installer et configurer TailwindCSS
        - [ ] Ajouter `NEXT_PUBLIC_API_URL` dans `.env.local`
        - [ ] Créer la page `/register` avec formulaire d'inscription
        - [ ] Créer la page `/login` avec formulaire de connexion
        - [ ] Implémenter le composant réutilisable `AuthForm` (inputs, erreurs, validation)
        - [ ] Appeler les endpoints backend (`/auth/register`, `/auth/login`, `/auth/refresh`)
        - [ ] Stocker le `accessToken` (temporarily in memory) et le `refreshToken` (secure storage)
        - [ ] Créer une page `/dashboard` protégée qui affiche les infos utilisateur
        - [ ] Gérer la déconnexion (supprimer token + appeler `/auth/logout`)
        - [ ] Tests manuels via navigateur / Postman / Insomnia

  - type: input
    id: api_url
    attributes:
      label: URL du backend API
      description: Adresse publique ou locale du backend SSO (ex: http://localhost:3000)
      placeholder: http://localhost:3000

  - type: textarea
    id: implementation_notes
    attributes:
      label: Notes d'implémentation
      description: Conseils et bonnes pratiques à respecter lors de l'implémentation.
      value: |
        - Préfère stocker l'access token en mémoire (éviter localStorage pour XSS).
        - Le refresh token peut être stocké dans un cookie HttpOnly si possible.
        - Valide les champs côté client (email, forces du mot de passe).
        - Affiche correctement les erreurs renvoyées par le backend (400/401).
        - Commence par une UI non stylée puis applique Tailwind pour itérer vite.

  - type: markdown
    attributes:
      value: |
        ## 🧪 Tests recommandés
        1. `POST /auth/register` → crée un utilisateur dans la DB (vérifier Prisma Studio)
        2. `POST /auth/login` → retourne `accessToken` + `refreshToken`
        3. Accéder à `/dashboard` avec le token (autorisation)
        4. `POST /auth/refresh` → obtenir un nouveau access token
        5. `POST /auth/logout` → supprimer la session / refresh token côté serveur

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **À fournir dans l'issue une fois terminée :**
        - Lien vers le commit/PR qui ajoute le front
        - Capture d'écran des pages `/login` et `/register`
        - Résultat des tests (ok / erreurs rencontrées)
